Add protobuf factory utilities
googleinterns/cloud-kms-oss-tools pull request #54
Opened 2020-07-07 20:32 UTC by ZacharyEspiritu

Resolves #53. 

In favor of the native `Client` interface approach (#38), this adds free functions that construct various protobufs for making gRPC requests.

Example usage of these functions in the context of the `GrpcClient` implementation:

https://github.com/googleinterns/cloud-kms-oss-tools/blob/3041fee8abbff81548303d0280c7b7812885bc7f/src/backing/client/grpc_client.cc#L59-L74

2020-07-08 16:00 UTC, ajfeldma-google requested changes

2020-07-08 16:00 UTC, ajfeldma-google commented on src/backing/client/proto_util/proto_make.cc
> +AsymmetricSignRequest MakeAsymmetricSignRequest(
This code may be too trivial to be worth factoring out into a function. Having a separate function may actually make things less clear.

2020-07-08 16:00 UTC, ajfeldma-google commented on src/backing/client/proto_util/proto_make.cc
> +GetPublicKeyRequest MakeGetPublicKeyRequest(
This code may be also be too trivial to be worth factoring out into a function.

2020-07-08 16:00 UTC, ajfeldma-google commented on src/backing/client/proto_util/proto_make.cc
> +Digest MakeDigest(Digest::DigestCase type, std::string digest_bytes) {
Consider using `string_view` for the function argument. Then, there's no reason to use `std::move` because a copy is being made no matter what.

2020-07-09 19:40 UTC, ZacharyEspiritu commented
Currently blocked by #58 due to Client interface rework to fix linking issues (moved to draft).

2020-07-16 19:49 UTC, ZacharyEspiritu commented
Closing to make a PR with a cleaner diff.

2020-07-16 19:49 UTC, closed without merging