Add external data utilities
googleinterns/cloud-kms-oss-tools pull request #61
Opened 2020-07-13 15:12 UTC by ZacharyEspiritu

Resolves #45. Blocked by #59 (draft for now).

Adds external data utilities for attaching engine-native objects to OpenSSL structs.

2020-07-21 20:49 UTC, ZacharyEspiritu commented
I've marked this as ready for review because even though it technically depends on #70, it appears that GitHub will, at least, automatically update the base branch of the PR  to master once #70 is merged so then this can be merged immediately after.

2020-07-27 15:00 UTC, tonyliaoss commented on src/bridge/ex_data_util/ex_data_util.cc
> +int rsa_index = kUninitializedIndex;
Make this static if `rsa_index` is only used in this file?

2020-07-27 15:00 UTC, tonyliaoss commented on src/bridge/ex_data_util/ex_data_util.cc
> +int engine_index = kUninitializedIndex;
Same here

2020-07-27 15:00 UTC, tonyliaoss commented on src/bridge/ex_data_util/ex_data_util.cc
> +Status AttachRsaKeyToOpenSslRsa(backing::RsaKey *rsa_key, RSA *rsa) {
What happens when `rsa_key` or `rsa` is a nullptr? Add a unit test for it?

2020-07-27 15:00 UTC, tonyliaoss commented on src/bridge/ex_data_util/ex_data_util.cc
> +Status AttachEngineDataToOpenSslEngine(EngineData *data, ENGINE *engine) {
Same here for `engine` and `data`

2020-07-27 15:00 UTC, tonyliaoss commented on src/bridge/ex_data_util/ex_data_util.cc
> +StatusOr<backing::RsaKey *> GetRsaKeyFromOpenSslRsa(const RSA *rsa) {
Same here

2020-07-27 15:00 UTC, tonyliaoss commented on src/bridge/ex_data_util/ex_data_util.cc
> +StatusOr<EngineData *> GetEngineDataFromOpenSslEngine(const ENGINE *engine) {
Same here

2020-07-27 15:02 UTC, ZacharyEspiritu commented on src/bridge/ex_data_util/ex_data_util.cc
> +int rsa_index = kUninitializedIndex;
Didn't mark as `static` since it's within an anonymous namespace, but if it's clearer can add `static`

2020-07-27 15:03 UTC, ZacharyEspiritu commented on src/bridge/ex_data_util/ex_data_util.cc
> +int engine_index = kUninitializedIndex;
See above

2020-07-27 15:33 UTC, tonyliaoss commented on src/bridge/ex_data_util/ex_data_util.cc
> +int rsa_index = kUninitializedIndex;
Yeah I'd say mark them static too for clarity.

2020-07-27 15:33 UTC, tonyliaoss submitted a review, later dismissed

2020-08-03 16:53 UTC, ajfeldma-google requested changes

2020-08-03 16:53 UTC, ajfeldma-google commented on src/bridge/ex_data_util/ex_data_util.h
> +void FreeExternalIndicies();
`s/Indicies/Indices`

2020-08-03 16:53 UTC, ajfeldma-google commented on src/bridge/ex_data_util/ex_data_util.cc
> +  return Status();
I think it would be better not to rely on the default constructor of `Status`. Is there an `OkStatus()` method of some sort that you can use?

2020-08-03 16:53 UTC, ajfeldma-google commented on src/bridge/ex_data_util/ex_data_util.cc
> +  auto ex_data = RSA_get_ex_data(rsa, index);
In general, prefer to spell out the return type explicitly unless it's really obvious: https://google.github.io/styleguide/cppguide.html#Type_deduction

In this case, knowing `ex_data` is `void*` is probably important.

2020-08-03 16:53 UTC, ajfeldma-google commented on src/bridge/ex_data_util/ex_data_util_test.cc
> +  auto rsa = MakeRsa();
Similar to the comment above (and for the whole file), prefer to spell out the return type explicitly unless it's really obvious: https://google.github.io/styleguide/cppguide.html#Type_deduction

2020-08-03 16:53 UTC, ajfeldma-google commented on src/bridge/ex_data_util/ex_data_util_test.cc
> +  ASSERT_THAT(AttachRsaKeyToOpenSslRsa(nullptr, rsa.get()), IsOk());
If retrieving a null `RsaKey` is an error, should setting one be allowed?

2020-08-03 17:02 UTC, ZacharyEspiritu commented on src/bridge/ex_data_util/ex_data_util_test.cc
> +  ASSERT_THAT(AttachRsaKeyToOpenSslRsa(nullptr, rsa.get()), IsOk());
Setting to nullptr is useful since it allows us to null-out when we free the `RsaKey` at a later point. However, when you call `Get...`,  the caller should check if the returned `RsaKey` is null anyways (just in case the invariants got screwed up somewhere, or the application passed in a bad `RSA` struct). Thus, returning an error status on a null `RsaKey` reduces some repetition down the line for callers to have to do a `if (rsa_key == nullptr) { ... }` check every time there's a `Get...`.

2020-08-03 21:08 UTC, ajfeldma-google approved these changes

2020-08-03 21:08 UTC, ajfeldma-google commented on src/bridge/ex_data_util/ex_data_util.cc
> +  return Status::kOk;
It looks like absl is going to have a free function `OkStatus()`: https://github.com/abseil/abseil-cpp/blob/1995c6a3c2f9080160d9d8716504dc004e5e1ec0/absl/status/status.h#L362

2020-08-10 13:55 UTC, tonyliaoss approved these changes

2020-08-10 14:41 UTC, merged