Add ClientContextFactory for GrpcClient implementation
googleinterns/cloud-kms-oss-tools pull request #65
Opened 2020-07-16 20:18 UTC by ZacharyEspiritu

Part of #42. Blocked by #58 and #64.

Adds a `ClientContextFactory` for making `grpc::ClientContext`s; defined in this way primarily for testing.

2020-07-21 20:16 UTC, ZacharyEspiritu commented
I'm un-drafting this PR so it can be reviewed, though note that bridge layer test cases are failing due to the `ERR_load_strings` pthread segmentation fault as discussed earlier.

2020-07-22 16:44 UTC, tonyliaoss submitted a review, later dismissed

2020-07-22 16:44 UTC, tonyliaoss commented on src/backing/client/grpc_client/client_context_factory.h
> +// TODO(zesp): There are other `grpc::ClientContext` options that may be useful
Maybe link this TODO to an issue instead? In case it doesn't get addressed during your internship.

2020-07-22 20:18 UTC, ZacharyEspiritu commented
Figured out this approach for solving the segmentation fault issues in `ERR_load_strings`:

https://github.com/googleinterns/cloud-kms-oss-tools/blob/ab52bec0f25b40bf0ad6cba39c3df498cd19a830/src/bridge/error/BUILD#L32-L39

I don't know if this is the best approach at the moment, but this does allow the tests to pass the normal `libengine.so` still seems to be loaded by the OpenSSL CLI just fine.

2020-07-27 17:52 UTC, tonyliaoss submitted a review, later dismissed

2020-07-27 19:44 UTC, ajfeldma-google requested changes

2020-07-27 19:44 UTC, ajfeldma-google commented on src/backing/client/grpc_client/client_context_factory_test.cc
> +  SystemClock::time_point time(real_clock.Now());
Consider making the test fully deterministic by hard-coding the time.

2020-07-27 22:31 UTC, ajfeldma-google submitted a review, later dismissed

2020-07-27 22:31 UTC, ajfeldma-google commented on src/backing/client/grpc_client/client_context_factory_test.cc
>    SystemClock real_clock;
I don't suppose you need `real_clock` anymore?

2020-08-03 14:03 UTC, tonyliaoss approved these changes

2020-08-03 14:56 UTC, ajfeldma-google approved these changes

2020-08-03 15:13 UTC, merged